# Slicing i 2d array
2D lister er tungvint å slice i 2 dimensjoner
- kan slice ut flere rader
    - men kan ikke slice kolonner
- indeksnotasjonen [][] har begrensede muligheter
    
2D array mye enklere
- indeksnotasjonen [ , ] større muligheter
- kan aksessere rektangulære bokser hvor som helst i et 2d array

Under vises noen eksempel:

In [1]:
import numpy as np
arr = np.array([np.arange(11,16), np.arange(21, 26), np.arange(31, 36), np.arange(41, 46), np.arange(51, 56)])
print(arr)

[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]


In [2]:
# To hele rader (rad 0 og 1)
arr[:2]

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [3]:
# Hel kolonne - som vektor
arr[:, 2]

array([13, 23, 33, 43, 53])

In [4]:
# Hel kolonne - som kolonnevektor
arr[:, 2:3]

array([[13],
       [23],
       [33],
       [43],
       [53]])

In [5]:
print(arr)

[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]


In [6]:
# To hele kolonner
arr[:,1:3]

array([[12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [7]:
# 2 x 2 midt i arrayet
arr[2:4, 1:3]

array([[32, 33],
       [42, 43]])

In [8]:
# 2 x 2 øverst venstre
arr[:2, :2]

array([[11, 12],
       [21, 22]])

In [9]:
# Hele arrayet unntatt venstre kolonne
arr[:,1:]

array([[12, 13, 14, 15],
       [22, 23, 24, 25],
       [32, 33, 34, 35],
       [42, 43, 44, 45],
       [52, 53, 54, 55]])

## Mutering ved 2d slicing
Vi kan også mutere et array ved 2d slicing
- NB: som før, antall element inn må være lik antall element ut
- og størrelse på boksen inn lik størrelse ut

Noen typiske eksempler:
- bytte innhold på to rader eller to kolonner
- bytte innhold på to rektangulære bokser i arrayet

## Generelt om å bytte innhold på to variable
I Python veldig enkelt å bytte innhold på to immuterbare variable
- f.eks. heltall, flyttall, streng...

Gjør bare slik:

In [10]:
x = 1
y = 2
x, y = y, x
print(x, y)

2 1


In [11]:
# mens mange andre prog.språk må gjøre slik (som også funker i Python)
x = 1
y = 2
temp = x
x = y
y = temp
print(x, y)

2 1


Med muterbare variable er det ikke like enkelt:
    - den ene blir nødvendigvis mutert før den andre
    - og begge ender opp med samme innhold

Eksempel: Prøver å bytte to rader i arrayet vårt:

In [12]:
print(arr)
print()
arr[0], arr[1] = arr[1], arr[0]
print(arr)

[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]

[[21 22 23 24 25]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]


Og temp-trikset virker ikke direkte heller:
- (hvorfor ikke? Jo, temp blir samme array-objekt som arr[2]
    - og endres dermed i linje 3 når arr[2] endres)

In [13]:
print(arr, '\n')
temp = arr[2]
arr[2] = arr[3]
arr[3] = temp
print(arr)

[[21 22 23 24 25]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]] 

[[21 22 23 24 25]
 [21 22 23 24 25]
 [41 42 43 44 45]
 [41 42 43 44 45]
 [51 52 53 54 55]]


Hva virker da?
- må ta en __kopi__ av det arrayet som først brukes på høyre side

In [14]:
print(arr,'\n')
temp = arr[3].copy()
arr[3] = arr[4]
arr[4] = temp  
print(arr)

[[21 22 23 24 25]
 [21 22 23 24 25]
 [41 42 43 44 45]
 [41 42 43 44 45]
 [51 52 53 54 55]] 

[[21 22 23 24 25]
 [21 22 23 24 25]
 [41 42 43 44 45]
 [51 52 53 54 55]
 [41 42 43 44 45]]


Med dette i boks kan vi kjøre i gang med mutering av 2d array ved slicing:

In [15]:
# Bytte første og siste kolonne:
print(arr,'\n')
temp = arr[:,0].copy()
arr[:,0] = arr[:,-1]
arr[:,-1] = temp
print(arr)

[[21 22 23 24 25]
 [21 22 23 24 25]
 [41 42 43 44 45]
 [51 52 53 54 55]
 [41 42 43 44 45]] 

[[25 22 23 24 21]
 [25 22 23 24 21]
 [45 42 43 44 41]
 [55 52 53 54 51]
 [45 42 43 44 41]]


In [16]:
# Bytte 2x2 øvre høyre med 2x2 nedre venstre
print(arr,'\n')
temp = arr[:2,-2:].copy()
arr[:2,-2:] = arr[-2:,:2]
arr[-2:,:2] = temp
print(arr)

[[25 22 23 24 21]
 [25 22 23 24 21]
 [45 42 43 44 41]
 [55 52 53 54 51]
 [45 42 43 44 41]] 

[[25 22 23 55 52]
 [25 22 23 45 42]
 [45 42 43 44 41]
 [24 21 53 54 51]
 [24 21 43 44 41]]


In [17]:
# Endre alt unntatt ytterste tall til 0.0
arr[1:-1,1:-1] = 0
print(arr)
# NB: Vanligvis må vi sette inn et eksakt like stort array som vi tar ut
# Unntaket er at vi kan gi inn ett eneste tall, 
# dette vil da bli satt i hele det aktuelle området

[[25 22 23 55 52]
 [25  0  0  0 42]
 [45  0  0  0 41]
 [24  0  0  0 51]
 [24 21 43 44 41]]


## Oppsummering
Slicing i 2D array gir slagkraftige muligheter
- kan brukes både på høyre side
    - til selektiv uthenting av data fra array
- og på venstre side
    - for mutering
- og dermed også både venstre og høyre
    - for å stokke om på innhold i arrayet
    
For mutering, f.eks. bytting av rader, kolonner, ...
- vær påpasselig med kopiering, ellers blir tallene bare like