# List comprehension
En mer kompakt måte å lage lister på i Python
- gjør i prinsippet det samme som å lage en liste med for-løkke og append()
- men lar oss skrive for-løkka inni listeparentesen
    - slipper dermed unna med ei kodelinje, i stedet for flere
    
Vi går rett på noen eksempler:

In [1]:
# Lage ei liste med kvadrattallene fra 1..100, vanlig løkke
kvadrat_tall = []
for x in range(1,11):
    kvadrat_tall.append(x**2)
    
print(kvadrat_tall)

# Lage ei liste med kvadrattallene fra 1..100, list comprehension
kvadrat_tall = [x**2 for x in range(1,11)]

print(kvadrat_tall) 

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [2]:
import numpy as np

# Liste med kvadratrøtter av tallene 1..10
røtter = []
for x in range(1,11):
    røtter.append(np.round(np.sqrt(x), 2))

print(røtter)

røtter = [np.round(np.sqrt(x),2) for x in range(1,11)]

print(røtter)

[1.0, 1.41, 1.73, 2.0, 2.24, 2.45, 2.65, 2.83, 3.0, 3.16]
[1.0, 1.41, 1.73, 2.0, 2.24, 2.45, 2.65, 2.83, 3.0, 3.16]


## Vi kan også ha  med if-setning i en list comprehension
- hvis ikke alle tall i serien skal med
- tilsvarende som vi ville brukt if-setning i ei for-løkke med append()

In [5]:
# Eksempel: har en enkel funksjon for å teste om noe er primtall
def is_prime(num):
    for n in range(2, num // 2 + 1):
        if num % n == 0:
            return False
    return True

# Lage ei liste av primtall opp til 100
primtall = []
for n in range(2,100):
    if is_prime(n):
        primtall.append(n)
print(primtall)

primtall = [x for x in range(2,100) if is_prime(x)]

print(primtall)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


## Kan også lage lister av lister
Må da ha to listeparenteser inni hverandre
- tre for lister av lister av lister, osv.

In [6]:
import numpy as np

## Kan også lage lister av lister med list comprehension
gangetabell = []
for i in range(1,11):
    gangetabell.append([]) # legger til ny rad
    for j in range(1,11):
        gangetabell[-1].append(i * j) # legger til nytt produkt bakerst i rada

print(np.array(gangetabell))

gangetabell = [[i * j for j in range(1,11)] for i in range(1,11)]

print(np.array(gangetabell))

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


Vel å merke, med numpy array kan dette løses på mer effektiv måte __uten__ list comprehension
- lager array direkte
    - multiplisere en rad-vektor 1..10 men en kolonne-vektor 1..10
- slipper dermed å gå i ei dobbel løkke og lage ett og ett tall

In [7]:
gangetabell = np.array(range(1,11)) * np.array(range(1,11)).reshape(10,1)

print(gangetabell)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


## Siste eksempel
- både 2d liste og if-setning inni
    - pluss vise at det kan brukes for alt mulig, ikke bare tall

In [8]:
turneringstabell = []
antall_deltagere = 8
for i in range(antall_deltagere):
    turneringstabell.append([])
    for j in range(antall_deltagere):
        if i == j:
            turneringstabell[-1].append('X')
        else:
            turneringstabell[-1].append('-')
print(np.array(turneringstabell))

turneringstabell = [['X' if i == j else '-' for j in range(antall_deltagere)] for i in range(antall_deltagere)]

print(np.array(turneringstabell))

[['X' '-' '-' '-' '-' '-' '-' '-']
 ['-' 'X' '-' '-' '-' '-' '-' '-']
 ['-' '-' 'X' '-' '-' '-' '-' '-']
 ['-' '-' '-' 'X' '-' '-' '-' '-']
 ['-' '-' '-' '-' 'X' '-' '-' '-']
 ['-' '-' '-' '-' '-' 'X' '-' '-']
 ['-' '-' '-' '-' '-' '-' 'X' '-']
 ['-' '-' '-' '-' '-' '-' '-' 'X']]
[['X' '-' '-' '-' '-' '-' '-' '-']
 ['-' 'X' '-' '-' '-' '-' '-' '-']
 ['-' '-' 'X' '-' '-' '-' '-' '-']
 ['-' '-' '-' 'X' '-' '-' '-' '-']
 ['-' '-' '-' '-' 'X' '-' '-' '-']
 ['-' '-' '-' '-' '-' 'X' '-' '-']
 ['-' '-' '-' '-' '-' '-' 'X' '-']
 ['-' '-' '-' '-' '-' '-' '-' 'X']]


## Oppsummering
List comprehension gir en mer kompakt og elegant skrivemåte når vi skal lage lister
- skrive for-løkka inni listeparentesen
    - i stedet for separate kodelinjer med liste = [], for..., append...
    
List comprehension er gjerne litt mer effektiv enn tilsvarende "vanlig" for-løkke
- men innebærer fortsatt en implisitt løkke
- ikke noen voldsom effektivitetsbesparelse

Dvs., bruk gjerne list comprehension der du syns det gjør koden mer kompakt og forståelig
- men ikke hvis du tvert imot syns den blir vanskeligere å forstå
- f.eks. med 2d-liste og if-else inni blir det kanskje litt tricky?