## Regulære tallserier: range, arange, linspace
Ofte trenger vi regulære serier av tall

Å taste inn lange serier av tall blir tungvint
- trenger funksjoner for å lage seriene automatisk

### Tre ofte brukte funksjoner
- range()
    - standard Python-funksjon
    - lager et generatorobjekt (fordel: tar svært lite minneplass)
    - kan KUN lage serier av heltall
- numpy.arange() og numpy.linspace()
    - lager numpy array (bruker mer plass, men fordel hvis vi trengte et array)
    - kan lage både heltall og flyttall

In [ ]:
## range(fra_og_med, til_men_ikke_med, stegverdi) - kan ta tre argument

print(list(range(0, 7, 1)))   # stegverdi 1, teller naturlig oppover
# [0, 1, 2, 3, 4, 5, 6]

print(list(range(3, 10, 2)))  # stegverdi 2, starter på 3, bare oddetall
# [3, 5, 7, 9]

print(list(range(10, 0, -3))) # med negativ stegverdi kan vi telle baklengs
# [10, 7, 4, 1]

: 

In [ ]:
## Vi trenger ikke gi inn alle tre argumentene til range()
print(list(range(0,7)))     # range(0,7) gir akkurat samme som range(0,7,1) ovenfor
# [0, 1, 2, 3, 4, 5, 6]

## ... og hvis startverdien er 0, kan vi utelate den også
print(list(range(7)))       # range(7) gir samme som range(0,7) og range(0,7,1)
# [0, 1, 2, 3, 4, 5, 6]

### numpy.arange()
numpy.arange() virker tilsvarende som range()
- kan ta tre argumenter: __fra_og_med__, __til_men_ikke_med__, __stegverdi__
- stegverdi kan droppes hvis den skal være 1
- fra_og_med kan droppes hvis den skal være 0

Men to viktige forskjeller
- arange lager et array
- arange kan også lage flyttall, og ha desimaltall som stegverdi
    - mens range bare kan ha heltall

In [ ]:
##Eksempler
import numpy as np
print(np.arange(7))   # hele tall, stegverdi 1
# [0 1 2 3 4 5 6]
print(np.arange(0.5,1.5,0.1))  # stegverdi 0.1
# [0.5 0.6 0.7 0.8 0.9 1.0 1.1 1.2 1.3 1.4]

### numpy.linspace()
Denne funksjonen kan oppnå det samme som arange(). 
Forskjellen ligger i hva vi må gi inn som argument. 

Til linspace er argumentene __fra_og_med, til_og_med, antall_verdier__

Eksempel:

In [ ]:
import numpy as np
print(np.linspace(0.5, 1.4, 10))  # gir samme resultat som arange(0.5, 2.5, 0.1) over
# [0.5 0.6 0.7 0.8 0.9 1.0 1.1 1.2 1.3 1.4]

__numpy.linspace__ kan være litt enklere enn __numpy.arange__
- hvis vi vet hva vi ønsker som endepunkter
- men ikke er så nøye med eksakt hva punktene mellom er
    - bare de er mange nok'
- F.eks. hvis vi ønsker 30 verdier fra og med 1 til og med 7:

In [ ]:
import numpy as np
print(np.linspace(1,7,30))