# Todimensjonale datastrukturer - oppretting og konvertering

Ofte nyttig med todimensjonale data, f.eks.
- lister av lister
- lister med tupler
- 2d array (matriser)

Bruksområder:
- matriseregning i matematikken (Matematikk 3)
    - med en masse bruksområder i naturvitenskap og ingeniørfag
- alle slags situasjoner hvor vi har data i tabellform
    - f.eks. temperaturmålinger hver time hver dag
        - hvor hvert døgn er en ny rad
        - og hver kolonne en gitt time det døgnet
    - kampresultater for ulike fotballag i en serie
    - ...


## Indeksering i todimensjonale data
Må nå bruke 2 indekser for å finne enkeltelement:
- [rad][kolonne] for liste og tuppel (og array)
- [rad,kolonne] - kun for array

In [ ]:
import numpy as np

liste_2d = [[1,2,3], [4,5,6], [7,8,9]]
tuple_2d = ((1,2,3), (4,5,6), (7,8,9))
print(liste_2d[1][-1]) # 6
print(tuple_2d[0][1]) # 2
arr = np.array(liste_2d)
print(arr[2,0]) #7
print(liste_2d[1,-1]) # Feil

In [ ]:
# En indeks gir ei hel rad
print(liste_2d[0])
print(arr[-1])
rad = arr[0]
print(rad[1])

## Lage todimensjonale array
### Teknikk 1: Ved å skrive tallene direkte, f.eks. i liste av lister
- upraktisk for store array

In [4]:
liste_av_lister = [[3, 4, 1, 9], [2, 0, 0, 7], [9, 1, 0, 2]]
tabell = np.array(liste_av_lister)
print(tabell)

[[3 4 1 9]
 [2 0 0 7]
 [9 1 0 2]]


### Teknikk 2: lage 1d array, så gjøre om til 2d
Fordel, fins noen hendige metoder, som f.eks.
- np.zeros() - lager array med bare nuller
- np.ones() - lager array med bare enere
- np.arange(), np.linspace() - lager regulære tallserier
- ...

In [5]:
import numpy as np
matrise = np.zeros(12)  # lager et 1D array med 12 nuller
print(matrise)
print()
matrise.resize(3,4) # gjør om til 3 rader, 4 kolonner
print(matrise)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Forskjell på array.resize() og array.reshape()
- __resize() er muterende__ ; gjør endring __i__ originalt arrayobjekt
- __reshape() lager en kopi__ på nytt sted i minnet, original uendret

In [6]:
# resize() er muterende
a = np.arange(8)
print(id(a))
print(a)
a.resize(2, 4)
print(id(a))
print(a)

4397126768
[0 1 2 3 4 5 6 7]
4397126768
[[0 1 2 3]
 [4 5 6 7]]


In [7]:
# reshape() er ikke-muterende
import numpy as np
b = np.arange(8)
c = b.reshape(2,4)
print(id(b), id(c))
print(b)
print(c)

4481197968 4481196816
[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


In [8]:
# resize() fyller på med nuller hvis vi har for få element
a = np.arange(8)
print(id(a))
print(a)
a.resize(2, 5)
print(id(a))
print(a)

4481199984
[0 1 2 3 4 5 6 7]
4481199984
[[0 1 2 3 4]
 [5 6 7 0 0]]


In [9]:
# resize() kutter element hvis vi har for mange
a = np.arange(8)
print(id(a))
print(a)
a.resize(2, 3)
print(id(a))
print(a)

4403835792
[0 1 2 3 4 5 6 7]
4403835792
[[0 1 2]
 [3 4 5]]


In [ ]:
# reshape() klikker hvis antallet ikke stemmer
import numpy as np
b = np.arange(8)
c = b.reshape(2,5)
print(id(b), id(c))
print(b)
print(c)

## Konvertere mellom array, liste, tuppel
Endimensjonalt: trivielt med funksjoner list(), tuple(), numpy.array()

In [11]:
import numpy as np
liste = [1,2,3]
print(tuple(liste), np.array(liste))
tuppel = (1, 2, 3)
print(list(tuppel), np.array(tuppel))
arr = np.arange(1,4)
print(tuple(arr), list(arr))


(1, 2, 3) [1 2 3]
[1, 2, 3] [1 2 3]
(np.int64(1), np.int64(2), np.int64(3)) [np.int64(1), np.int64(2), np.int64(3)]


### Konvertering til 2d array
Todimensjonalt: np.array() virker i dybden på 2d lister og tupler, lister med tupler, etc.

In [12]:
list2d = [[1,2,3], [4,5,6], [7,8,9]]
tup2d = ((1,2,3), (4,5,6), (7,8,9))
list_of_tup = [(1,2,3), (4,5,6), (7,8,9)]
tup_of_lists = [[1,2,3], [4,5,6], [7,8,9]]
print(np.array(list2d))
print(np.array(tup2d))
print(np.array(list_of_tup))
print(np.array(tup_of_lists))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Konvertering fra 2d array
standardfunksjonene list() og tuple() tar bare toppnivået

In [13]:
arr = np.arange(8)
arr.resize(2,4)
print(arr)
print(tuple(arr))
print(list(arr))
print(list(tup2d))

[[0 1 2 3]
 [4 5 6 7]]
(array([0, 1, 2, 3]), array([4, 5, 6, 7]))
[array([0, 1, 2, 3]), array([4, 5, 6, 7])]
[(1, 2, 3), (4, 5, 6), (7, 8, 9)]


### Konvertering fra 2d-array, forts.
numpy har metoden __tolist()__ som gjør dybdekonvertering til liste av liste

In [14]:
arr = np.arange(8)
arr.resize(2,4)
print(arr)
print(arr.tolist())

[[0 1 2 3]
 [4 5 6 7]]
[[0, 1, 2, 3], [4, 5, 6, 7]]


# Oppsummering
Ofte har vi bruk for todimensjonale datastrukturer, f.eks.
- lister av lister
- tupler av tupler
- lister av tupler, ...
- todimensjonale array (ofte kalt matriser)

Matriser er ofte enklest å opprette ved å
- først lage et 1d array (vektor)
- så gjøre om til 2d med resize eller reshape
    - hhv. muterende og ikke-muterende
    
I 2d datastrukturer må vi bruke 2 indekser for å aksessere enkeltelement